name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.repository == 'codeforvision/covid19-az'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build
        run: |
          npm install
          npx @11ty/eleventy
          npx minify-json dist/data
          npx terser dist/assets/main.js -o dist/assets/main.js -c toplevel -m toplevel
          npx terser dist/assets/test.js -o dist/assets/test.js -c toplevel -m toplevel
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: covid19-az.info
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: Deploy
