name: Fetch data

on:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  build:
    if: github.repository == 'codeforvision/covid19-az'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Get the latest stats
        run: |
          curl -sS https://corona.lmao.ninja/v2/countries/azerbaijan | jq 'del(.countryInfo)' | jq 'del(.updated)' > src/data/stats.json
          git commit -am "Update stats.json" || echo "No updates to commit"
      - name: Get the latest timeseries
        run: |
          curl -sS https://pomber.github.io/covid19/timeseries.json | jq .Azerbaijan > src/data/timeseries.json
          git commit -am "Update timeseries.json" || echo "No updates to commit"
      - name: Create Pull Request with updated data files
        uses: peter-evans/create-pull-request@v3
        with:
          title: Automated data update
          body: This is an auto-generated PR with data updates.
          branch: data-updates
          reviewers: NARKOZ
